# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2]
        activerecord: [6.1, '7.0', 7.1]

    runs-on: ubuntu-latest

    name: Test against Ruby ${{ matrix.ruby }} / ActiveModel ${{ matrix.activerecord }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      env:
        ACTIVE_RECORD_VERSION: ~> ${{ matrix.activerecord }}.0
      run: bundle install --jobs 4 --retry 3
    - name: Run specs
      env:
        ACTIVE_RECORD_VERSION: ~> ${{ matrix.activerecord }}.0
      run: bundle exec rspec spec --backtrace
